name: Firebase Deploy (WIF)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (root)
        run: npm ci

      - name: Lint (if available)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script defined; skipping"
          fi

      - name: Run tests (if available)
        run: |
          if npm run | grep -q "test"; then
            npm test -- --ci || npm test
          else
            echo "No test script defined; skipping"
          fi

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}

      - name: Generate Workbox precache (injectManifest)
        run: npx workbox-cli@6 injectManifest --config workbox.config.cjs

      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Deploy Hosting (and Functions if present)
        env:
          FIREBASE_TOKEN: ${{ steps.auth.outputs.access_token }}
        shell: bash
        run: |
          set -euo pipefail
          TARGETS="hosting"
          if [ -f functions/package.json ]; then
            echo "Detected functions/package.json. Installing and building Functions..."
            (cd functions && npm ci && npm run build)
            TARGETS="hosting,functions"
          else
            echo "No functions/package.json found. Deploying Hosting only." 
          fi
          firebase deploy --project "${{ vars.GCP_PROJECT_ID }}" --only "$TARGETS" --token "$FIREBASE_TOKEN"