name: Firebase Deploy (WIF)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (root, include dev)
        run: npm ci --include=dev

      - name: Verify TypeScript React types
        run: |
          npm ls @types/react @types/react-dom || npm i -D @types/react @types/react-dom

      - name: Build project
        run: npm run build

      - name: Generate Workbox precache (injectManifest)
        run: npx workbox-cli@6 injectManifest --config workbox.config.cjs

      - name: Authenticate to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install and build Functions
        run: |
          cd functions
          npm ci
          npm run build

      - name: Deploy Hosting and Functions via Firebase CLI
        env:
          FIREBASE_TOKEN: ${{ steps.auth.outputs.access_token }}
        run: |
          firebase deploy --project ${{ vars.GCP_PROJECT_ID }} --only hosting,functions --token "$FIREBASE_TOKEN"